Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  ExcludedMethods: []
  Exclude:
    - '*.gemspec'
    - 'spec/**/*.rb'
    - 'wallaby.gemspec'

Style/SingleLineMethods:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/rails'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/**/*'
    - 'spec/dummy/*'
    - 'spec/views/wallaby/resources/*/_xml.html.erb_spec.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()
    '%W': ()
