inherit_gem:
  wallaby-cop: rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/rails'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/**/*'
    - 'spec/dummy/*'
    - 'spec/views/wallaby/resources/*/_xml.html.erb_spec.rb'
    - 'gemfiles/**/*'

Rails/OutputSafety:
  Enabled: false
